site_name: AI with Python
site_description: Personal Python notes about maths and data analysis
site_author: Alessandro

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light mode

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.arithmatex: #MathJax support is built-in.
      generic: true
  - pymdownx.tabbed
  - toc:
      permalink: true
#MathJax lib
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js
  - javascripts/mermaid.js

plugins:
  - search
nav:
  - index.md
  - Introduction:
      - 001-introduction/index.md
      - 001-introduction/machine-learning-problems.md
  - Preliminaries:
      - 002-preliminaries/data-manipulation.md
      - 002-preliminaries/pandas.md
      - 002-preliminaries/linear-algebra.md
      - 002-preliminaries/eigencomposition.md
      - 002-preliminaries/calculus.md
      - 002-preliminaries/automatic_differentiation.md
      - 002-preliminaries/probability_statistics.md
  - Linear neural networks for regression:
      - 003-linear_neural_networks_for_regression/linear_regression.md
  - Linear neural networks for classification:
      - 004-linear_neural_networks_for_classification/softmax_regression.md
  - Multilayer perceptors:
      - 005-multi_layer_perceptrons/multilayer_perceptrons.md
      - 005-multi_layer_perceptrons/mlp_implementation.md
  - Convolutional networks for image classification:
      - 007-convolutional_neural_networks/index.md
      - 007-convolutional_neural_networks/implementation.md
  - Recurring neural networks:
      - 009-recurring_neural_networks/index.md
      - 009-recurring_neural_networks/vanilla_rnn_example.md
  - Transformers and attention mechanisms:
      - 011-transformers_and_attention_mechanisms/index.md
      - 011-transformers_and_attention_mechanisms/attention_layer_example.md
      - 011-transformers_and_attention_mechanisms/transformer_example.md

